### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by svblsvljb** [unusec/steam-auto-confirm-accept#2]
Logging in as:  crsov
internal/fs/utils.js:779
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (7)
    at Object.writeFile (fs.js:1436:5)
    at FileStorage.saveFile.FileStorage.writeFile (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/file-manager/index.js:68:5)
    at SteamUser._handlers.<computed> (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/steam-user/components/logon.js:294:18)
    at SteamUser._handleMessage (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:315:20)
    at CMClient._netMsgReceived (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.<computed> (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:315:20)
    at TCPConnection._readPacket (/home/aru/.apps/starteble/steam-auto-confirm-accept/node_modules/steam-client/lib/tcp_connection.js:183:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by guvenada** [comment]
any solution?
